// Generated by CoffeeScript 1.10.0
(function() {
  var onDOMContentLoaded, onTabShow, sendTabMessage, urls;

  urls = ['chrome://newtab/', 'chrome-search://local-ntp/local-ntp.html'];

  sendTabMessage = function(tab) {
    var iof;
    iof = urls.indexOf(tab.url);
    if (iof !== -1) {
      chrome.tabs.sendMessage(tab.id, 'activate');
    }
  };

  onTabShow = function(tabId, changeInfo, tab) {
    if (changeInfo.status === 'complete') {
      sendTabMessage(tab);
    }
  };

  onDOMContentLoaded = function() {
    chrome.tabs.query({
      active: true,
      currentWindow: true
    }, function(tabs) {
      sendTabMessage(tabs[0]);
    });
  };

  // chrome.tabs.onUpdated.addListener(onTabShow);

  chrome.webNavigation.onDOMContentLoaded.addListener(function(event) {
    onDOMContentLoaded();
  });

  document.addEventListener('DOMContentLoaded', function(event) {
    onDOMContentLoaded();
  });

}).call(this);
