// Generated by CoffeeScript 1.10.0
(function() {
  var getById, getOption, infopop, saveAlsoHideByCssSelectors, saveAlsoHideLogo, saveAlsoHideNavbar, saveAlsoHidePromo, saveAlsoHideSearchbar, saveOptions, setOption;

  infopop = function(message) {
    var infodiv, timer;
    infodiv = document.createElement('div');
    timer = null;
    infodiv.style.width = '400px';
    infodiv.style.backgroundColor = '#efe';
    infodiv.style.border = '1px solid #7c7';
    infodiv.style.padding = '10px';
    infodiv.style.margin = '20px';
    infodiv.style.borderRadius = '10px';
    infodiv.innerHTML = message;
    document.body.appendChild(infodiv);
    timer = window.setTimeout(function() {
      return document.body.removeChild(infodiv);
    }, 3500);
  };

  saveOptions = function() {
    saveAlsoHideLogo();
    saveAlsoHideSearchbar();
    saveAlsoHideNavbar();
    saveAlsoHidePromo();
    saveAlsoHideByCssSelectors();
    infopop('Settings saved!');
  };

  setOption = function(key, value, cb) {
    var typeOfCallback, val;
    typeOfCallback = typeof cb;
    if (typeOfCallback !== 'function') {
      cb = function() {};
    }
    val = {};
    val[key] = value;
    chrome.storage.sync.set(val, cb);
  };

  getOption = function(key, cb) {
    var typeOfKey;
    typeOfKey = typeof key;
    if (typeOfKey === 'string') {
      key = [key];
    }
    chrome.storage.sync.get(key, function(res) {
      cb(res);
    });
  };

  getById = function(id) {
    return document.getElementById(id);
  };

  saveAlsoHideLogo = function() {
    var el;
    el = getById('cbAlsoHideLogo');
    setOption(el.id, el.checked);
  };

  saveAlsoHideSearchbar = function() {
    var el;
    el = getById('cbAlsoHideSearchbar');
    setOption(el.id, el.checked);
  };

  saveAlsoHideNavbar = function() {
    var el;
    el = getById('cbAlsoHideNavbar');
    setOption(el.id, el.checked);
  };

  saveAlsoHidePromo = function() {
    var el;
    el = getById('cbAlsoHidePromo');
    setOption(el.id, el.checked);
  };

  saveAlsoHideByCssSelectors = function() {
    var el;
    el = getById('cbAlsoHideByCssSelectors');
    setOption(el.id, el.value);
  };

  chrome.storage.sync.get(['cbAlsoHideLogo', 'cbAlsoHideSearchbar', 'cbAlsoHideNavbar', 'cbAlsoHidePromo', 'cbAlsoHideByCssSelectors'], function(dataObject) {
    var el, key;
    for (key in dataObject) {
      try {
        el = getById(key);
        if (dataObject[key] === true) {
          el.checked = true;
        } else if (dataObject[key].length > 0) {
          el.value = dataObject[key];
        }
      } catch (undefined) {}
    }
  });

  document.getElementById('btnSave').onclick = saveOptions;

}).call(this);
